/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me/memberships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My Memberships
         * @description The tenants the caller belongs to (a partner's is their org's).
         */
        get: operations["list_my_memberships"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{slug}/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Devices */
        get: operations["list_devices"];
        put?: never;
        /** Create Device */
        post: operations["create_device"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{slug}/dives": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dives */
        get: operations["list_dives"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{slug}/dives/{number}/calibration-refusal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Clear Dive Calibration Refusal
         * @description Clear dive ``number``'s standing calibration refusal, so it is
         *     fitted again (idempotent): for a change its labels don't show.
         */
        delete: operations["clear_dive_calibration_refusal"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{slug}/dives/{number}/calibration-source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Clear Dive Calibration Source
         * @description Unlink dive ``number`` from any borrowed calibration (idempotent).
         */
        delete: operations["clear_dive_calibration_source"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{slug}/dives/{number}/calibration-source/{source_number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Dive Calibration Source
         * @description Dive ``number`` borrows dive ``source_number``'s laser calibration.
         *
         *     400 on a self-link; 404 if either dive is missing from the tenant.
         */
        put: operations["set_dive_calibration_source"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{slug}/dives/{number}/calibration-target": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Clear Dive Calibration Target
         * @description Unlink dive ``number`` from any calibration target (idempotent): it
         *     leaves the checkerboard cohort. A standing refusal is left as it is.
         */
        delete: operations["clear_dive_calibration_target"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{slug}/dives/{number}/calibration-target/{target_number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Dive Calibration Target
         * @description Dive ``number`` was shot against calibration target
         *     ``target_number``: it enters the checkerboard cohort, and a standing
         *     calibration refusal expires.
         *
         *     404 if the dive is missing from the tenant or no target has that
         *     number.
         */
        put: operations["set_dive_calibration_target"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{slug}/dives/{number}/labels/{kind}/needs-reprocess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Raise Needs Reprocess
         * @description Redraw dive ``number``'s ``kind`` frames: the dive re-enters that
         *     kind's preprocessing, and the JPEGs are redrawn where they are.
         *     Incomplete labels only unless ``only_incomplete=false``.
         */
        put: operations["raise_needs_reprocess"];
        post?: never;
        /**
         * Clear Needs Reprocess
         * @description Withdraw a redraw of dive ``number``'s ``kind`` frames (idempotent:
         *     0 when none was asked for).
         */
        delete: operations["clear_needs_reprocess"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{slug}/label-studio-projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Label Studio Project Ids
         * @description Label Studio project ids with live labels of ``kind``.
         */
        get: operations["list_label_studio_project_ids"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{slug}/membership": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Membership */
        get: operations["get_my_membership"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Cleared */
        Cleared: {
            /** Cleared */
            cleared: number;
        };
        /** Device */
        Device: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "lite" | "lite_flatport" | "mobile" | "multilens" | "mono" | "scout";
            /** Serial */
            serial: string;
        };
        /** DeviceCreate */
        DeviceCreate: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "lite" | "lite_flatport" | "mobile" | "multilens" | "mono" | "scout";
            /** Serial */
            serial: string;
        };
        /** Dive */
        Dive: {
            /** Calibration Source Number */
            calibration_source_number: number | null;
            /** Calibration Target Number */
            calibration_target_number: number | null;
            /**
             * Dived At
             * Format: date-time
             */
            dived_at: string;
            /** Name */
            name: string | null;
            /** Number */
            number: number;
            /**
             * Priority
             * @enum {string}
             */
            priority: "low" | "high" | "none";
            /** Slate Template Number */
            slate_template_number: number | null;
        };
        /** Flagged */
        Flagged: {
            /** Flagged */
            flagged: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MyMembership */
        MyMembership: {
            /** Is Admin */
            is_admin: boolean;
            /** Role */
            role: string;
        };
        /** MyTenant */
        MyTenant: {
            /** Is Admin */
            is_admin: boolean;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Slug */
            slug: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_my_memberships: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyTenant"][];
                };
            };
        };
    };
    list_devices: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_device: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_dives: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dive"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_dive_calibration_refusal: {
        parameters: {
            query?: {
                /** @description why, kept with the clear */
                reason?: string | null;
            };
            header?: never;
            path: {
                number: number;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_dive_calibration_source: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: number;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_dive_calibration_source: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: number;
                source_number: number;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dive"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_dive_calibration_target: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: number;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_dive_calibration_target: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: number;
                target_number: number;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dive"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    raise_needs_reprocess: {
        parameters: {
            query?: {
                only_incomplete?: boolean;
            };
            header?: never;
            path: {
                number: number;
                kind: "laser" | "head_tail" | "species" | "slate";
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Flagged"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_needs_reprocess: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: number;
                kind: "laser" | "head_tail" | "species" | "slate";
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cleared"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_label_studio_project_ids: {
        parameters: {
            query: {
                kind: "laser" | "head_tail" | "species" | "slate";
                incomplete?: boolean;
                /** @description laser only: the auto-accept gate is done here */
                gated?: boolean | null;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": number[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_membership: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyMembership"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
